version: "3"
networks:
  spring-sql-network
services:
  database:
    image: mysql:latest
    networks:
      - spring-sql-network
    environment:
      - MYSQL_ROOT_PASSWORD: root
      - MYSQL_DATABASE: DanPizza
  application-DanPizza:
    image: dan-pizza
    networks:
      - spring-sql-network
    ports:
      - "9090:8080"
    depends_on:
      - database


